version: '3.7'

services:

  oowlish-tracker:
    container_name: oowlish-tracker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3004 -w db.json
    ports:
      - "3004:3004"
    volumes:
      - ./data:/data
    restart: always